name: Run Python Script

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  run-python-script:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    env:
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code
    
    - name: Set up Python
      uses: actions/setup-python@v4  # Set up Python environment
      with:
        python-version: '3.12'  
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Login to W&B
      run: |
        wandb login
        
    - name: Run Python script
      run: |
        python tier_exp copy.py  
